### ISSUE TITLE
Switches stopped working. 

### ISSUE THREAD

**Issue by bindingofman** [bj00rn/ha-saleryd-ftx#1]
I was so happy when I found this intergrstion for HA, and it's been working great 👍🏼
Now the switch.saleryd_hrv_away_mode, boost and home fails to call service.
I tried to roll back to 2.0.11 this version was working with my firmware 4.1.1. I see the supported firmware for the LOKE 01 is 4.1.5, where can I get this?
I reached out to Saleryd and looked on their website, but no luck in tracking down the file. 
Any help much appreciated

**Comment by bj00rn** [comment]
Glad you like it!

Technically earlier firmware versions below 4.1.5 are still supported. However, versions below 4.1.5 have problems where websocket server becomes unresponsive after a while. Thats why i added the notice. I believe this is a hardware problem. The installerad came and fixed it by replacing the wifi module. 

A workaround is to reset the FTX system by cutting power and the connection will come back to life (for a while at least). When the error occurs you will see State.RETRYING in the Connection state sensor. 

Is the normal web interface still accessible and working when you get the error?

**Comment by bindingofman** [comment]
Yes, I've had to restart it quite regularly to regain conection.
I'll contact the installers to see if they will upgrade the hardware, I used Aerius.
There is no problem with the Web interface all functions well.
In developer tools I can call services and change boost/home/away.
It's just the switch. that's not working for me. I'm using the latest 2023.7.3 HA

Here is the log when I try to turn boost mode on with the switch toggle. It looks like it's a HA code issue?
2023-07-30 19:17:43.074 DEBUG (MainThread) [custom_components.saleryd_hrv] Finished fetching saleryd_hrv data in 0.008 seconds (success: True)
2023-07-30 19:17:45.068 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547339554704] ServiceRegistry.call() got an unexpected keyword argument 'limit'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 848, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1248, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saleryd_hrv/switch.py", line 42, in turn_on
    self.hass.services.call(
TypeError: ServiceRegistry.call() got an unexpected keyword argument 'limit'
2023-07-30 19:17:48.065 WARNING (MainThread) [custom_components.saleryd_hrv] Your control system version is (4.1.1). This integration has been verified to work with the following versions: 4.1.5
2023-07-30 19:17:48.068 ERROR (MainThread) [custom_components.saleryd_hrv] Your control system version is (4.1.1). This integration is incompatible with the following versions: 4.1.1
2023-07-30 19:17:48.071 DEBUG (MainThread) [custom_components.saleryd_hrv] Finished fetching saleryd_hrv data in 0.006 seconds (success: True)

**Comment by bj00rn** [comment]
Hmm, i don't think your error above is related to the firmware (apart from it loosing connection from time to time)

I'ts probably something that has changed in HA 2023. 

I will try and recreate the error

**Comment by bj00rn** [comment]
Should be fixed now in pre release 3.0.0-alpha.1

I've not yet tested HA 2023 support.. results may vary

<img width="626" alt="image" src="https://github.com/bj00rn/ha-saleryd-ftx/assets/10961167/a2184c3f-b481-44e1-9d21-80edd90810fe">

In HACS under integration -> Redownload -> Enable beta versions

Restart Home assistant

**Comment by bj00rn** [comment]
> Awesome, just tested it and all back to normal 👍🏼 much appreciate your work with this. Tusen tack

Kul med lite feedback! Trodde det bara var jag som använde denna. Kom gärna med buggrapporter och förslag på förbättringar.

**Comment by bj00rn** [comment]
@bindingofman did a new release 2.2.1 to stop spamming when firmware is unsupported

**Comment by bindingofman** [comment]
> @bindingofman did a new release 2.2.1 to stop spamming when firmware is unsupported

That's great 👍🏼 🙂
